apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: textchess-msk8
build:
  artifacts:
    - image: engine
      context: ENGINE
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile

    - image: enginemovehandler
      context: EngineMoveHandler
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile

    - image: usermovehandler
      context: UserMoveHandler
      sync:
        manual:
          - src: "index.js"
            dest: ./routes
          - src: "rabbitMqSender.js"
            dest: ./MIDDLEWARE
      docker:
        dockerfile: Dockerfile

    # - image: enginemovereceiver
    #   context: EngineMoveReceiver
    #   sync:
    #     manual:
    #       - src: "index.js"
    #         dest: .
    #   docker:
    #     dockerfile: Dockerfile

    # - image: enginemovesender
    #   context: EngineMoveSender
    #   sync:
    #     manual:
    #       - src: "index.js"
    #         dest: .
    #   docker:
    #     dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
      # - infra/SKAFFOLD/*.yml
      - infra/configmap.yml
      - infra/ingress-rules.yml
      - infra/enginemovehandler-depl.yml
      - infra/rabbitmq-depl.yml
      - infra/usermovehandler-depl.yml
      - infra/engine-depl.yml
      # - infra/enginemovereceiver-depl.yml
      # - infra/enginemovesender-depl.yml
