apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-deployment
  labels:
    app: engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
    spec:
      containers:
        - name: engine
          image: iem22/textchess_ms_engine:v1
